### ISSUE TITLE
npm run dev - error  in ./src/server/index.js

### ISSUE THREAD

**Issue by drunkod** [rlindskog/vueniverse#12]
ERROR  Failed to compile with 1 errors                               4:38:12 PM

 error  in ./src/server/index.js

Module build failed: Error: Couldn't find preset "env" relative to directory "/home/alex"
    at /home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/alex/vueniverse/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/alex/vueniverse/node_modules/babel-loader/lib/index.js:50:20)

module.js:472
    throw err;
    ^

Error: Cannot find module '/home/alex/vueniverse/dist/server/main.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

**Comment by drunkod** [comment]
` npm install --save-dev babel-cli babel-preset-env`
not help

**Comment by rlindskog** [comment]
@drunkod I'm not exactly sure what's wrong, could you give me any other details on the problem?  What did you run to get this error?

**Comment by drunkod** [comment]
The error occurs only on the local.
Thanks for the answer.
